### ISSUE TITLE
Issue after package name migration

### ISSUE THREAD

**Issue by dvaghela** [defval/di#48]
`go get github.com/defval/di`

go: github.com/defval/di@v1.11.2: parsing go.mod:
        module declares its path as: github.com/goava/di
                but was required as: github.com/defval/di
                
 `go get github.com/goava/di` works

**Comment by dvaghela** [comment]
Trying to clean my mod cache and see if it works, might just be my local issue

**Comment by dvaghela** [comment]
Nope, didn't help

**Comment by defval** [comment]
@dvaghela Hi, sorry about that. I forgot to create a new release, but I have fixed it now. Everything should be working fine.

**Comment by fabiante** [comment]
```sh
go get github.com/defval/di
go: downloading github.com/defval/di v1.12.0
go: added github.com/defval/di v1.12.0
```

Can confirm that this works now. Thanks!
